# Olympic Data Analysis

## 1. Import Libraries

In [ ]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt

## 2. Load Data

In [49]:
bios_df = pd.read_csv("./bios.csv")

In [50]:
bios_df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

## 3. Initial Data Inspection

In [51]:
bios_df.shape

(145500, 16)

In [14]:
bios_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  str
 1   Sex            145500 non-null  str
 2   Full name      145500 non-null  str
 3   Used name      145500 non-null  str
 4   Born           143772 non-null  str
 5   Died           34042 non-null   str
 6   NOC            145499 non-null  str
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  str
 9   Affiliations   95832 non-null   str
 10  Nick/petnames  9145 non-null    str
 11  Title(s)       399 non-null     str
 12  Other names    7167 non-null    str
 13  Nationality    8259 non-null    str
 14  Original name  30739 non-null   str
 15  Name order     7844 non-null    str
dtypes: int64(1), str(15)
memory usage: 17.8 MB

In [52]:
bios_df.isna().sum()

Roles                 0
Sex                   0
Full name             0
Used name             0
Born               1728
Died             111458
NOC                   1
athlete_id            0
Measurements      37667
Affiliations      49668
Nick/petnames    136355
Title(s)         145101
Other names      138333
Nationality      137241
Original name    114761
Name order       137656
dtype: int64

In [53]:
bios = bios_df.copy()

## 4. Data Cleaning

##### 4.1 Used name cleaning

In [55]:
bios['Used name_clean'] = (
        bios['Used name']
        .str.replace('•', ' ')
        .str.replace(r'\s+', ' ')
        .str.strip()
)

##### 4.2 Full name cleaning

In [78]:
bios['Full name_clean'] = (
    bios['Full name']
    .str.replace('•', ' ')
    .str.replace(r'\s+', ' ')
    .str.strip()
)

##### 4.3 Measurements Cleaning

In [ ]:
bios['Height_cm'] = np.nan
bios['Weight_min_kg'] = np.nan
bios['Weight_max_kg'] = np.nan

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Title(s),Other names,Nationality,Original name,Name order,Used name_clean,Full name_clean,Height_cm,Weight_min_kg,Weight_max_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,"François Joseph Marie Antoine ""Jean-François"" ...",NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,Arnaud Benjamin Boetsch,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jean Borotra,Jean Laurent Robert Borotra,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,Jacques Marie Stanislas Jean Brugnon,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaN,NaN,Albert Canet,Henry Albert Canet,NaN,NaN,NaN

In [ ]:
height = bios['Measurements'].str.extract(
    r'(\d+(?:[.,]\d+)?)\s*cm',
    expand=False
)

bios['Height_cm'] = height.str.replace(',', '.', regex=False).astype(float)

In [213]:
weight_text = bios['Measurements'].str.extract(
    r'(?:/\s*)?([\d\s,–-]+)\s*kg',
    expand=False
)

In [230]:
def parse_weight(value):
    if pd.isna(value):
        return np.nan, np.nan

    value = value.strip()

    # Ondalıklı kilo: 77,5
    if re.fullmatch(r'\d+,\d+', value):
        weight = float(value.replace(',', '.'))
        return weight, weight

    # Aralık: 62–65 veya 62-65
    if re.fullmatch(r'\d+\s*[–-]\s*\d+', value):
        numbers = [float(x) for x in re.findall(r'\d+', value)]
        return min(numbers), max(numbers)

    # Çoklu kilo: 74, 82 veya 76, 77, 79
    numbers = re.findall(r'\d+', value)

    if numbers:
        numbers = [float(x) for x in numbers]
        return min(numbers), max(numbers)

    return np.nan, np.nan

In [231]:
weights = weight_text.apply(parse_weight)

bios['Weight_min_kg'] = weights.str[0]
bios['Weight_max_kg'] = weights.str[1]